# Задача 1. «Треугольник с максимальным периметром»
Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью ­ функция возвращает 0.

In [2]:
#Находжение периметра
def Perimetr (a, b, c):
    if (a+b)>c and (a+c)>b and (b+c)>a:
        return int(a+b+c)
    else:
        return 0
#

length=int(input('Введите длину массива'))
mas=[]
P=int(0)
for i in range(length):
    mas.append(int(input()))
#mas=sorted(mas, reverse=True)
print(mas)
for a in range(len(mas)-2):
    for b in range(a+1, len(mas)-1):
        for c in range(b+1, len(mas)):
            if P<Perimetr(mas[a], mas[b], mas[c]):
                P=Perimetr(mas[a], mas[b], mas[c])
print("Периметр=", P)

Введите длину массива3 3


ValueError: invalid literal for int() with base 10: '3 3'

# Задача 2. «Максимальное число»
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

In [12]:
def per_mas(n, m):
    for i in range(n):
        j=0
        for j in range(m):
            yield i, j

length=int(input('Введите длину массива'))
nums=[]
max="0"
rez=""
for i in range(length):
    nums.append(input())

for i in range(len(nums)):
    for j in range(i+1, len(nums)):
        if int(nums[j][0])>int(nums[i][0]):
            nums[j], nums[i]=nums[i], nums[j]
        elif (int(nums[j][0])==int(nums[i][0])):
            for k, m in per_mas(len(nums[j]), len(nums[i])):
                #print(nums[j][k], "and", nums[i][m])
                if int(nums[j][k])>int(nums[i][m]):
                    nums[j], nums[i]=nums[i], nums[j]
                    break
                        
for i in range(len(nums)):
    rez=rez+str(nums[i])
print(rez)

Введите длину массива1
1
1


# Задача 3. «Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.


In [82]:
import numpy
def per_mas(n, m):
    for i in range(n):
        for j in range(m):
            yield i, j
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i, j in per_mas(len(massiv[0]), len(massiv)):
    k=j
    l=i
    while k<len(massiv[0]) and l<len(massiv):
        if massiv[i][j]>massiv[l][k]:
            massiv[i][j], massiv[l][k]=massiv[l][k], massiv[i][j]
        k=k+1
        l=l+1
            
print("\n\n")
print(massiv)

Введите m и n:4 5
[[ 5 17 16 16 17]
 [ 6  8  8 13  6]
 [13 10 11  3 17]
 [11  6 18  4  7]]



[[ 4  3 13  6 17]
 [ 6  5  7 16 16]
 [ 6 10  8  8 17]
 [11 13 18 11 17]]


<ipython-input-82-401fb204b888>:7: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  massiv = numpy.random.random_integers(0, 20, size=(m, n))
